site_name: IWrok Test
site_url: https://mohamed-kaizen.github.io/IWork-test
site_author: Mohamed Nesredin
site_description: >-
  A test by IWork

repo_name: Mohamed-Kaizen/IWork-test
repo_url: https://github.com/Mohamed-Kaizen/IWork-test/
edit_uri: https://github.com/Mohamed-Kaizen/IWork-test/docs/

copyright: Copyright &copy; 2020 Mohamed Nesredin

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "iwrok_test.settings")
            - django.setup()
          rendering:
            show_source: true
      watch:
        - iwrok_test
        - users
        - product

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Command: 'command.md'
  - Reference:
      - product:
          - Models: "reference/product/models.md"
          - Utils: "reference/product/utils.md"
      - Users:
          - Adapter: "reference/users/adapter.md"
          - Context Processors: "reference/users/context_processors.md"
          - Forms: "reference/users/forms.md"
          - Models: "reference/users/models.md"
          - Validators: "reference/users/validators.md"
          - Views: "reference/users/views.md"


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.details


extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'js/mermaid.min.js'
    - 'js/termynal.js'
    - 'js/custom.js'
